config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "registrations", confirmations: 'confirmations' }

  get 'notre_histoire', to: 'pages#notre_histoire', as: :notre_histoire
  get 'notre_equipe', to: 'pages#notre_equipe', as: :notre_equipe
  get 'nos_actions', to: 'pages#nos_actions', as: :nos_actions
  get 'nous_soutenir', to: 'pages#nous_soutenir', as: :nous_soutenir
  get 'eshop', to: 'pages#eshop', as: :eshop
  get 'post_sign_up', to: 'pages#post_sign_up', as: :confirmation_compte

  resources :teams do
    resources :participants, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
  end

  resources :profiles do
    resources :participants, only: [:show, :destroy]
      member do
        get :mon_inscription
      end
    resources :teams, only: [:show, :destroy] do
      member do
        put :accept_player, :deny_player, :close_subscriptions
      end
    end
    # resources :pulls, only: [:new, :create, :delete]
  end

  get 'nous_contacter', to: 'contacts#new', as: :nous_contacter
  get 'sponsor', to: 'contacts#sponsor', as: :sponsor
  resources :contacts, only: [:create]
  resources :pulls, only: [:new, :create, :delete]
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :pull
  enum role: { player: 1, captain: 2, spectator: 3 }
  enum gender: { male: 0, female: 1 }
  enum status: %i[inactive active pending denied finished]
  validates :first_name, :last_name, :gender, :phone_number, :role, :party, :dinner, presence: true, allow_blank: false
  validates :phone_number, format: { with: /\A(?:(?:\+|00)33|0)\s*[6-7](?:[\s.-]*\d{2}){4}\z/, message: "Format incorrect, vérifie que tu aies rentré le bon numéro" }

  scope :role, -> { where(captain: true) }
  scope :role, -> { where(player: true) }
  scope :role, -> { where(spectator: true) }
  scope :party, -> { where(party: true) }

  private

  def send_welcome_email
    ProfileMailer.welcome(self).deliver_now
  end

  def email
    "#{Profile.find(id).user.email}"
  end

  def name
    "#{first_name} #{last_name}"
  end

  def admin
    "#{Profile.find(id).user.admin}"
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[show edit update mon_inscription]

  def new
    @profile = Profile.new
    authorize @profile
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    authorize @profile
    if @profile.save && @profile.role == "player"
      redirect_to teams_path
    elsif @profile.save && @profile.role == "spectator"
      redirect_to mon_inscription_profile_path(@profile)
    else
      render 'new'
      flash[:notice] = "Une erreur est survenue, veillez vérifier que vous avez bien rempli tous les champs demandés :)"
    end
  end

  def show
    @team = Team.find_by(user_id: current_user.id)
    authorize @profile
  end

  def edit
    authorize @profile
    @profile.save
  end

  def update
    @profile.update(profile_params)
    authorize @profile
    @profile.save
    redirect_to profile_path(@profile), notice: 'Votre profil a été mis à jour'
  end

  def mon_inscription
    @team = Team.find_by(user_id: current_user.id)
    @participant = Participant.where(user_id: current_user.id).last
    authorize @profile
  end

  private

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :user_id, :gender, :phone_number, :role, :dinner, :party)
  end

  def set_profile
    @profile = current_user.profile
  end
end

app/views/profiles/_form.html.erb
<div class="col-xs-12 col-sm-10 offset-sm-1 col-md-6 offset-md-3">
  <div class="form-group">
      <%= simple_form_for @profile do |f| %>
        <%= f.input :first_name, label: "Prénom"  %>
        <%= f.input :last_name, label: "Nom de Famille" %>
        <%= f.input :phone_number, label: "Numéro de téléphone" %>
        <%= f.input :dinner, label: "Participeras-tu au dîner ?", as: :radio_buttons, collection: [[ true, "Bien entendu !"], [false, "Non, pas le temps"]], label_method: :second, value_method: :first  %>
        <%= f.input :party, label: "Participeras-tu à la soirée ?", as: :radio_buttons, collection: [[ true, "Oui !"], [false, "Non merci"]], label_method: :second, value_method: :first %>
        <div class="align-buttons">
          <%= f.submit "Valider", class: "btn btn-primary"%>
          <% end %>
          <%= link_to "Retour", profile_path(@profile), class: "btn btn-primary"%>
        </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="santerre-form">
    <h1>Mettre à jour votre profil</h1>
    <%= render 'form'%>
  </div>
</div>

app/views/profiles/mon_inscription.html.erb
 <div class="wrapper-gray-back">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="mon_inscription_card">
          <h1>Mon inscription</h1>
            <% if @profile.captain? %>
              <% if @profile.active? && @team.status == 'accepted' %>
                <p>Cher(e) capitaine de la très heureuse équipe <i><%= @team.name %></i>, un grand bravo, ton équipe a été acceptée! Nous sommes ravis que tu nous rejoignes pour ce si bel événement.</p>
                <p>Nous te faisons une entière et pleine confiance dans la constitution de ton équipe. Cette dernière doit être exactement la même que celle que tu nous as envoyée. Nous nous réservons le droit d'annuler la demande d'un joueur autre que ceux renseignés, sauf si cela est gentiment demandé en amont bien sûr!</p>
                <p>Allez on oublie pas de payer sa place !</p>
                <div class="align-buttons">
                <%= link_to 'Je paye ma place avec Lydia', "https://collecte.io/santerre-cup-iveme-edition-156010", class: 'btn btn-primary', target: "_blank" %>
                </div>
              <% elsif @profile.active? && @team.status =='pending' %>
                <p>Cher(e) capitaine de la très heureuse équipe <i><%= @team.name %></i>, ton équipe est en train d'être examiné par le Staff. Nous reviendrons vers toi très rapidement (max 2 jours) pour valider ou non ton équipe.
                <p>La bise,</p>
                <p>Le Staff</p>
              <% elsif @profile.finished? %>
                <p>C'est tout bon <strong><%= @profile.first_name %></strong>, maintenant que tu as payé ta place, tu es parfaitement en règle. On t'attend chaud bouillant le 29 Juin 2019 avec <i><%= @team.name %>.</i></p>
                <p>N'oublie pas de réviser tes gammes pour être prêt autant sur le plan taketike que tekenike, le niveau promet d'être solide cette année. </p>
                <p>Nous te réitérons notre confiance dans la constitution de ton équipe, pas de bêtises.</p>
                <p>Pour les informations pratiques, elles seront communiquées en temps et en heure, pas de panique.</p>
                <p>Avec tout notre amour,</p>
                <p>Le Staff</p>
              <% end %>
            <% elsif @profile.spectator? %>
              <% if @profile.denied? %>
                <p>Le Staff a malheureusement refusé votre demande ... Les places spectateurs sont très limitées, le Staff privilégie en effet les places pour les joueurs. Nous ne manquerons pas de te recontacter si jamais des places se libèrent.</p>
              <% elsif @profile.inactive? %>
                <p>Les places en tant que spectateur étant limitées, le Staff est en train d'étudier ta demande. Nous reviendrons très vite vers toi et tu devrais avoir une réponse sous les 2 jours. En attendant, tu peux découvrir les équipes déjà inscrites et les joueurs en cliquant sur le lien ci-dessous.</p>
                  <div class="align-buttons">
                    <%= link_to 'Voir toutes les équipes', teams_path, class: 'btn btn-primary' %>
                  </div>
              <% elsif @profile.active? %>
                <p>Le Staff a accepté votre demande ! <%= "Petit veinard 😉." if @profile.gender == "male"%><%= "Petite veinarde 😉." if @profile.gender == "female"%> Pour valider définitivement ton inscription, il ne te reste plus qu'à payer ta place sur la plateforme de notre partenaire Lydia.</p>
                <div class="align-buttons">
                    <%= link_to 'Je paye ma place avec Lydia', "https://collecte.io/santerre-cup-iveme-edition-156010", class: 'btn btn-primary', target: "_blank" %>
                </div>
              <% elsif @profile.finished? %>
                <p>C'est tout bon <%= @profile.first_name %>, tu as payé ta place, tu es parfaitement en règle. On t'attend chaud bouillant le 29 Juin 2019 pour encourager les joueurs et mettre le feu en tribune. Une récompense sera distribuée pour le meilleur spectateur, on dit ça on dit rien ...</p>
                <p>Pour les informations pratiques, elles seront communiquées en temps et en heure, pas de panique.</p>
                <p>Avec tout notre amour,</p>
                <p>Le Staff</p>
            <% else %>
              <p>Tu n'as pas encore fait de demande ou tu n'as aucune demande en cours. Envie de rejoindre une équipe ? Ou de créer la tienne ? N'hésite pas et fonce !</p>
              <div class="align-buttons">
              <%= link_to 'Voir toutes les équipes', teams_path, class: 'btn btn-primary' %>
              </div>
            <% end %>
          <% elsif @profile.player? && @profile.inactive? %>
            <% if !@participant.nil? && @participant.denied? %>
              <p>Capitaine <%= @participant.team.user.name %> a refusé que tu rejoignes son équipe <%= @participant.team.name %> !</p>
              <p>Nous sommes désolé pour toi, mais tu vas devoir te trouver une autre équipe ou créer ta propre équipe si tu veux participer à notre bel événement.</p>
              <div class="align-buttons">
                <%= link_to 'Voir toutes les équipes', teams_path, class: 'btn btn-primary' %>
              </div>
            <% else %>
              <p>Tu n'as pas encore fait de demande ou tu n'as aucune demande en cours. Envie de rejoindre une équipe ? Ou de créer la tienne ? N'hésite pas et fonce !</p>
              <div class="align-buttons">
              <%= link_to 'Voir toutes les équipes', teams_path, class: 'btn btn-primary' %>
              </div>
            <% end %>
          <% elsif @profile.active? %>
            <% if @participant.pending? %>
              <% if @profile.gender == "male"  %>
                <p>Mein lieber <%= @profile.user.name %>,</p>
              <% else %>
                <p>Meine liebe <%= @profile.user.name %>,</p>
              <% end %>
              <p>Patience,</p>
              <p><%= @participant.team.user.name %>, capitaine de la merveilleuse équipe <em><%= @participant.team.name %> </em>est en train d'étudier ta demande.</p>
              <p>Quoiqu'il arrive, il a reçu un email le prévenant que tu souhaitais rejoindre son équipe.</p>
              <p>Vive le XXIème siècle quand même.</p>
              <p>Avec tout notre amour,</p>
              <p>Le Staff</p>
              <div class="align-buttons">
                <%= link_to 'Voir toutes les équipes', teams_path, class: 'btn btn-primary' %>
                <%= form_tag profile_participant_path(@profile), method: :delete do %>
                  <%= submit_tag 'Annuler ma demande', data: { confirm: 'Es-tu sûr de vouloir annuler ta demande ?'}, class: 'btn btn-primary'  %>
                <% end %>
              </div>
            <% elsif @participant.accepted? %>
              <% if @profile.gender == "male"  %>
                <p>Mein lieber <%= @profile.user.name %>,</p>
              <% else %>
                <p>Meine liebe <%= @profile.user.name %>,</p>
              <% end %>
              <p><%= @participant.team.user.name %> a accepté votre demande. Tu es maintenant officiellement un membre de l'équipe <i><%= @participant.team.name %></i>. Pour valider définitivement ton inscription, il ne te reste plus qu'à payer ta place sur la plateforme de notre partenaire Lydia.</p>
              <p>Allez hop hop hop, on se dépêche !</p>
              <%= link_to 'Je paye ma place avec Lydia', "https://collecte.io/santerre-cup-iveme-edition-156010", class: 'btn btn-primary',target: "_blank" %>
            <% else @participant.finished? %>
              <p>C'est tout bon <strong><%= @profile.first_name %></strong>, maintenant que tu as payé ta place, tu es parfaitement en règle. On t'attend chaud bouillant le 29 Juin 2019 avec <i><%= @participant.team.name %>.</i></p>
              <p>N'oublie pas de réviser tes gammes pour être prêt autant sur le plan taketike que tekenike, le niveau promet d'être solide cette année.</p>
              <p>Pour les informations pratiques, elles seront communiquées en temps et en heure, pas de panique.</p>
              <p>Avec tout notre amour,</p>
              <p>Le Staff</p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col col-md-8 offset-md-2">
      <div class="santerre-form">
        <h2>Pour valider définitivement ton compte, nous avons besoin de quelques renseignements supplémentaires sur toi</h1>

        <p>Nous avons besoin de ces renseignements pour vérifier l'identité des participants et assurer la sécurité de chacun.</p>

        <%= simple_form_for @profile, :url => { :action => "create" }  do |f| %>
          <%= f.input :first_name, label: 'Prénom', placeholder: "Zinedine" %>
          <%= f.input :last_name, label: 'Nom de famille', placeholder: "Zidane"%>
          <%= f.input :gender, label: 'Vous êtes', as: :radio_buttons, collection: [[ 'female', 'une femme'], [ 'male', 'un homme']], label_method: :second, value_method: :first %>
          <%= f.input :phone_number, label: "Votre numéro de téléphone", placeholder: '06.06.06.06.06' %>
          <%= f.input :role, label: "Quel est ton rôle ?", as: :radio_buttons, collection: [[:player, "Je suis un joueur"], [:spectator, "Je suis un spectateur"]], label_method: :second, value_method: :first %>
          <%= f.input :dinner, label: "Seras-tu présent au dîner ?", as: :radio_buttons, collection: [[ true, "Oui"], [false, "Non merci"]], label_method: :second, value_method: :first %>
          <%= f.input :party, label: "Participeras-tu à la soirée ?", as: :radio_buttons, collection: [[ true, "Bien entendu"], [false, "Non, c'est plus de mon âge"]], label_method: :second, value_method: :first %>
          <%= f.button :submit, "Créer mon profil", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="show-profile-card">
        <h1>Mon profil </h1>
        <p>Très chers tous, je m'appelle <strong><%= @profile.first_name%> <%=@profile.last_name %></strong>.<p>
        <% if @profile.gender == "male" %>
          <p>Je suis un (bel) <strong>homme</strong>,</p>
        <% else %>
          <p>Je suis une <strong>femme</strong>,</p>
        <% end %>
        <p>qui peut être <%= "jointe" if @profile.gender == "female" %><%="joint" if @profile.gender == "male" %> à l'adresse mail suivante : <strong><%= @profile.user.email %></strong></p>
        <p>ou alors par téléphone au <strong><%= @profile.phone_number %></strong>.</p>
        <% if !@profile.denied? %>
          <p>Pour cette IVème édition de la Santerre Cup, je serai là en tant que <strong>
            <% if @profile.role == "spectator" %>
              <% if @profile.gender == "male" %>
                spectateur</strong><%= ", si le Staff accepte ma demande." if @profile.status? == "pending" %></p>
              <% else %>
                spectatrice</strong><%= ", si le Staff accepte ma demande." if @profile.status? == "pending" %></p>
              <% end %>
            <% else %>
              <% if @profile.gender == "male" %>
                joueur.</strong></p>
              <% else %>
                joueuse.</strong></p>
              <% end %>
            <% end %>
          <% if @profile.dinner? %>
            <p> Je serai <strong><%= "présent" if @profile.male?%> <%= "présente" if @profile.female? %></strong> pour déguster l'excellent dîner que le Staff nous a prévu.</p>
          <% else %>
            <p>Bien que le dîner promet d'être excellent, <strong>je ne pourrai y assiter</strong>.</p>
          <% end %>
          <% if @profile.party? %>
            <p>Bien entendu, <strong>je participerai à la soirée</strong>.</p>
          <% else %>
            <p>La soirée étant trop tardive, <strong>je n'y participerai donc pas</strong>.</p>
          <% end %>
            <% end %>
          <p>Si jamais ces informations ne sont plus à jour, je peux à tout moment les éditer en cliquant sur le bouton juste en-dessous.</p>
          <div class="align-buttons">
            <%= link_to "Mettre à jour mes informations", edit_profile_path(@profile), class: "btn btn-primary" %>
            <% if Participant.where(user_id: current_user.id, status: 'accepted').empty? %>
              <%= link_to "Voir toutes les équipes", teams_path, class: 'btn btn-primary' %>
            <% else %>
              <%= link_to "Voir mon équipe", team_path(Participant.where(user_id: current_user.id, status: 'accepted')[0].team_id), class: 'btn btn-primary'%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>