config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "registrations", confirmations: 'confirmations' }

  get 'notre_histoire', to: 'pages#notre_histoire', as: :notre_histoire
  get 'notre_equipe', to: 'pages#notre_equipe', as: :notre_equipe
  get 'nos_actions', to: 'pages#nos_actions', as: :nos_actions
  get 'nous_soutenir', to: 'pages#nous_soutenir', as: :nous_soutenir
  get 'eshop', to: 'pages#eshop', as: :eshop
  get 'post_sign_up', to: 'pages#post_sign_up', as: :confirmation_compte

  resources :teams do
    resources :participants, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
  end

  resources :profiles do
    resources :participants, only: [:show, :destroy]
      member do
        get :mon_inscription
      end
    resources :teams, only: [:show, :destroy] do
      member do
        put :accept_player, :deny_player, :close_subscriptions
      end
    end
    # resources :pulls, only: [:new, :create, :delete]
  end

  get 'nous_contacter', to: 'contacts#new', as: :nous_contacter
  get 'sponsor', to: 'contacts#sponsor', as: :sponsor
  resources :contacts, only: [:create]
  resources :pulls, only: [:new, :create, :delete]
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.facebook.com/santerrecup/?ref=bookmarks" target="_blank"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    Ce site internet est réalisé avec <i class="fas fa-heart"></i> par le Staff
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-md navbar-light navbar-lewagon">

  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo.png"%>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Notre histoire", notre_histoire_path, class: "nav-link"   %>
      </li>
      <li class="nav-item">
        <%= link_to "Notre équipe", notre_equipe_path, class: "nav-link"   %>
      </li>
      <li class="nav-item">
        <%= link_to "Nos actions", nos_actions_path, class: "nav-link"   %>
      </li>
      <li class="nav-item">
        <%= link_to "Nous soutenir", nous_soutenir_path, class: "nav-link"   %>
      </li>
      <li class="nav-item">
        <%= link_to "Nous contacter", nous_contacter_path, class: "nav-link"   %>
      </li>
      <% if user_signed_in? && current_user.profile.nil? %>
        <li class="nav-item dropdown">
          <%= image_tag "ballondefoot.jpg", class: "avatar dropdown-toggle pointer", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mon profil", new_profile_path, class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% elsif user_signed_in? && current_user.profile.valid? %>
        <li class="nav-item dropdown">
          <%= image_tag "ballondefoot.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", admin_root_path, class: "dropdown-item" if current_user.admin? %>
            <%= link_to "Mon profil", profile_path(current_user), class: "dropdown-item" %>
            <%= link_to "Mon inscription", mon_inscription_profile_path(current_user.profile), class: "dropdown-item" %>
            <%= link_to "Mon équipe", profile_team_path(current_user.profile.id, Team.find_by(user_id: current_user.id).id), class: "dropdown-item" if current_user.profile.captain? %>
            <%= link_to "Voir les équipes", teams_path, class: "dropdown-item"%>
            <%= link_to "Je veux un pull", new_pull_path, class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "S'inscrire / se connecter", new_user_session_path, class: "nav-link login" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>