config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "registrations", confirmations: 'confirmations' }

  get 'notre_histoire', to: 'pages#notre_histoire', as: :notre_histoire
  get 'notre_equipe', to: 'pages#notre_equipe', as: :notre_equipe
  get 'nos_actions', to: 'pages#nos_actions', as: :nos_actions
  get 'nous_soutenir', to: 'pages#nous_soutenir', as: :nous_soutenir
  get 'eshop', to: 'pages#eshop', as: :eshop
  get 'post_sign_up', to: 'pages#post_sign_up', as: :confirmation_compte

  resources :teams do
    resources :participants, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
  end

  resources :profiles do
    resources :participants, only: [:show, :destroy]
      member do
        get :mon_inscription
      end
    resources :teams, only: [:show, :destroy] do
      member do
        put :accept_player, :deny_player, :close_subscriptions
      end
    end
    # resources :pulls, only: [:new, :create, :delete]
  end

  get 'nous_contacter', to: 'contacts#new', as: :nous_contacter
  get 'sponsor', to: 'contacts#sponsor', as: :sponsor
  resources :contacts, only: [:create]
  resources :pulls, only: [:new, :create, :delete]
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/eshop.html.erb
<h1>Yo yo</h1>

<%= User.all.each do |u| %>
  <%= print u.profile %>
<% end  %>


<%= Participant.all.each do |p| %>
  <%= print p.user.profile %>
<% end %>

app/views/pages/home.html.erb
<div class="wrapper-home-navbar">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-7 d-none d-lg-block">
        <%= image_tag "homepage.jpg", class: "photo-card" %>
      </div>
      <div class="col-md">
        <%= image_tag "logo.png", class: ".d-none .d-sm-block .d-lg-none img" %>
        <br>
        <h1>VISONS PLUS QU'UNE VICTOIRE</h1>
        <br>
        <h3>IVème édition</h3>
        <h3>29 Juin 2019</h3>
      </div>
    </div>
  </div>
</div>
<div class="wrapper-gray-home">
  <div class="container">
    <div class="row">
      <h2>La Santerre Cup en quelques mots</h2>
      <p>La Santerre Cup est un tournoi de football qui rassemble le temps d’une journée et d’une soirée 500 jeunes autour de projets solidaires ! Sur la journée se déroulent deux tournois de foot, un tournoi masculin et un autre féminin. À la fin de ceux-ci, joueuses et joueurs se retrouvent autour d’un repas convivial avant de prolonger le plaisir avec la soirée de clôture.</p>
      <p>Cependant, la Santerre Cup, c’est bien plus qu’un tournoi de foot. Association loi de 1901 depuis 2017, tous les bénéfices réalisés lors de chaque édition sont reversés à des associations caritatives. Lors de notre précédente édition en 2017, plus de 6000€ ont été reversés à nos 3 associations partenaires. Pour cette nouvelle édition, nous ne comptons pas nous arrêter en si bon chemin et sommes toujours à la recherche de nouveaux sponsors. Si vous voulez participez à notre beau projet, rendez-vous sur cette <%= link_to 'page', nous_soutenir_path %>. </p>
    </div>
    <div class="row">
      <div class="col-md-6 col-lg-3">
        <div class="card">
          <h1>Notre vision</h1>
          <p>Le sport est vecteur d’émotions, de valeurs et d’actions positives et universelles.</p>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="card">
          <h1>Notre mission</h1>
          <p>Organiser un événement sportif et solidaire au sein de notre Picardie natale.</p>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="card">
          <h1>Notre ambition</h1>
          <p>Devenir une référence des événements sportifs, jeunes et solidaires.</p>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="card">
          <h1>Nos valeurs</h1>
          <p>Partage, dépassement de soi, esprit d’équipe, solidarité, respect et engagement.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="wrapper-white-home">
  <div class="container">
    <div class="row">
      <div class="col">
        <h2>Découvrez la vidéo de la 3ème édition</h2>
        <iframe class="video-center" width="560" height="315" src="https://www.youtube.com/embed/Vwjcs30fjVA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>
<div class="wrapper-gray-home">
  <div class="container">
    <div class="row">
      <div class="col-md col-lg-8 offset-lg-2">
        <div class="contact-card">
          <h2>Envie de nous envoyer un petit mot doux ?</h2>
          <p>Nous serions ravi d’échanger avec vous. Plusieurs options : vous pouvez nous envoyer un petit mot doux à staff@santerrecup.com, sur notre page Facebook ou alors à travers <%= link_to 'ce formulaire', nous_contacter_path %> ! Nous tâcherons de vous répondre le plus rapidement possible.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/nos_actions.html.erb
<div class="wrapper-white-actions">
  <div class="container-fluid">
    <div class="row">
    <h1>Visons plus qu’une victoire</h1>
    <p>Depuis 2017, la Santerre Cup est une association de loi 1901 d’intérêt général. 100% des bénéfices réalisés grâce aux dons des sponsors et à la participation des joueurs et joueuses sont reversés à des associations caritatives. Voici les dons de la IIIème édition !</p>
    </div>
    <div class="row">
      <div class="nos-actions-card">
        <div class="col-lg-4 col-md-10">
          <%= image_tag "http://poussieresdevie.org/wp-content/uploads/2018/10/logo-pdv-grand.png", class: "d-none d-lg-block img-action" %>
        </div>
        <div class="col-lg-8 col-md">
          <h4>Poussières de vie<p> <%= link_to "(Visiter leur site internet)", "http://poussieresdevie.org", target: "_blank"%></p></h4>
          <p>Poussières de vie est une organisation à but non lucratif qui vient en aide aux populations défavorisées du Vietnam à Hô-Chi-Minh-Ville et dans la province de Kon Tum. L’association agit pour une intégration sociale et professionnelle réussie à travers différents projets d’éducation, de formation professionnelle et de développement personnel.</p>
          <p>La Santerre Cup lui a fait don de 2 000€ pour le lancement de son projet « Point Sport », initié par notre membre Auriane, qui donne accès au sport à 200 enfants issus de minorités ethniques et vivant dans des orphelinats à Kon Tum.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="nos-actions-card">
        <div class="col-lg-4 col-md-10">
          <img src="https://www.lettresadhesives.net/storage/stickers/sticker%20rose%20des%20vents%2012.png?frz-v=17" width="400" height="400" class="d-none d-lg-block img-action" >
        </div>
        <div class="col-lg-8 col-md">
          <h4>L’Arche la Rose des Vents Verpillères <p> <%= link_to "(Visiter leur site internet)", "https://www.le-site-de.com/l-arche-la-rose-des-vents-verpillieres_85222.html", target: "_blank"%></p></h4>
          <p>L’Arche la Rose des Vents Verpillères est un foyer d’hébergement et de services pour adultes en situation de handicap, situé à Verpillières.</p>
          <p>La Santerre Cup lui a reversé 2 000€ afin d’aménager un jardin thérapeutique pour les personnes qui y résident.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="nos-actions-card">
        <div class="col-lg-4 col-md-10">
          <%= image_tag "https://www.centreoscarlambret.fr/themes/oscar/assets/images/logo-centre-oscar-lambret.jpg", class: "d-none d-lg-block img-action-2" %>
        </div>
        <div class="col-lg-8 col-md">
          <h4>Le Centre Oscar Lambret<p> <%= link_to "(Visiter leur site internet)", "https://www.centreoscarlambret.fr", target: "_blank"%></p></h4>
          <p>Le Centre Oscar Lambert est un hôpital universitaire et centre régional spécialisé dans la lutte contre le cancer. Le centre Oscar Lambret a trois missions principales : le soin, la recherche et l’enseignement. Il prend plus de 22 000 patients en charge chaque année.</p>
          <p>La Santerre Cup lui versé 2 000€ afin de contribuer à faire progresser les recherches.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/notre_equipe.html.erb
<div class="wrapper-white-navbar">
  <div class="container-fluid">
    <div class="row">
      <h1>L’équipe-type pour la saison 2019/2020</h1>
      <p>Pour les uns, le sport est une passion depuis toujours et se pratique en compétition. Pour les autres, c’est un loisir hebdomadaire indispensable. Il y a aussi ceux pour qui c’est un moyen de se réunir. L’équipe de la Santerre Cup, c’est tout cela.</p>
      <p>Mais c’est aussi la certitude que quelle que soit sa pratique, le sport change les vies. L’équipe est également certaine que chacun doit agir positivement pour que le monde de demain soit meilleur. Pour chaque membre, la Santerre Cup est alors un bon moyen de faire passer ce message et de fédérer les jeunes autour de la solidarité.</p>
      <p style="margin: 0px auto 30px;">Enfin, nous sommes amis dans la vie, mais nos parcours sont diversifiés. C’est ce qui fait de nous une équipe soudée et complémentaire.</p>
      <%= image_tag "equipe.png", class: "photo-card-equipe" %>
    </div>
  </div>
</div>

app/views/pages/notre_histoire.html.erb
<div class="wrapper-white-navbar">
  <div class="container-fluid">
    <div class="row">
      <h1>La Santerre Cup, un événement sportif et bon enfant qui ne laisse personne indifférent</h1>
      <p>Originellement un tournoi de copains, la Santerre Cup s’est peu à peu développée et agrandie pour devenir un événement incontournable des Hauts-de-France. Très attachée à ses racines et profondément ancrée dans sa région, la Santerre Cup tient son nom de cette terre fertile où le tournoi est organisé et d’où sont originaires les fondateurs. On vous raconte notre histoire.</p>
    </div>
    <div class="row little-space">
      <div class="col-md-7">
        <h3>Au commencement était le football …</h3>
        <p>En 2014, les frères Gonzague et Pierre-Antoine Gru  imaginent ce qui s’appelle à l’époque « L’Estremons Cup ».</p>
        <p>Le principe de ce tournoi : délimiter les terrains avec  des « palox », qui servent à l’origine à stocker les récoltes de pommes de terre. Lors de cette première édition, 100 amis originaires des Hauts-de-France se sont réunis pour le sport et la fête.</p>
      </div>
      <div class="col-md">
      <%= image_tag "photo23.JPG", class: "photo-card" %>
      </div>
    </div>
  </div>
</div>
<div class="wrapper-gray">
  <div class="container-fluid">
    <div class="row little-space">
      <div class="col-md">
        <%= image_tag "photo5.JPG", class: "photo-card" %>
      </div>
      <div class="col-md-7">
        <h3>2015, la jeune génération entre en jeu !</h3>
        <p>Très motivés par la première édition, Donatien Dupuy, Martin de Becquincourt, Maxence Ammeux et Rodrigue Frassaint décident d’honorer leurs amis fondateurs. Ils reprennent le flambeau : même principe, même ambiance mais avec une réelle volonté d’accueillir plus de participants.</p>
        <p>Le 10 juin 2015, ce qui était devenu « la Santerre Cup IIème édition » offrait alors aux 250 participants une ambiance conviviale, sportive et festive.</p>
      </div>
      <div class="row big-space">
        <div class="col-md-7">
          <h3>2017, le bond en avant</h3>
          <p>En 2017, la IIIème édition prend une nouvelle dimension ! L’équipe s’agrandit encore avec l’engagement d’Albéric Decanter, Arthur Deffontaines, Auriane Buridard, Colombe Decarne et Jean Mennesson. En plus de continuer à démocratiser l’événement, l’ensemble du comité se fixe de nouveaux objectifs et décide d’associer cette rencontre sportive à la solidarité.</p>
          <p>La Santerre Cup devient alors une association loi 1901, rassemble désormais 450 participants, est soutenue par 31 partenaires et reverse 100% de ses bénéfices à des associations caritatives !</p>
        </div>
        <div class="col-md">
          <%= image_tag "photo8.JPG", class: "photo-card" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="wrapper-white-navbar">
  <div class="container">
    <div class="row">
      <div class="col-md">
        <h3>2019, la confirmation ?</h3>
        <p>Pour cette nouvelle édition, le comité souhaite confirmer l’élan pris par l’événement lors de la IIIème édition. Pour l’amour du sport, la joie de l’engagement, l’envie d’aider et la célébration d’être une fois de plus réunis autour de valeurs communes. Pour cette nouvelle édition, les objectifs sont d'accroître les inscriptions d'équipes féminines et d'augmenter les recettes pour reverser toujours plus aux associations caritatives. <%= link_to "Sponsors, à vous de jouer !", nous_soutenir_path %></p>
        <p>Un seul sport au menu, le football, pour réunir garçons et filles vers le même objectif de solidarité. Et le tout pour une entrée à 40€ tout compris.</p>
        <%= image_tag "photo4.JPG", class: "photo-card-small bottom-space" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/nous_soutenir.html.erb
<div class="wrapper-white-navbar">
  <div class="container-fluid">
    <h1>Vous souhaitez nous aider ? Vous êtes sur la bonne page</h1>
      <div class="row little-space">
        <div class="col-lg-6">
          <p>La Santerre Cup ne serait pas ce qu’elle est actuellement sans la générosité et la bienveillance de ses nombreux sponsors. C’est avec vos dons que nous pouvons proposer une prestation haut de gamme à un prix raisonnable tout en redistribuant tous nos bénéfices à des associations caritatives. Grâce à vous, le sport permet de rassembler le temps d’une journée près de 500 jeunes dans une ambiance festive et conviviale, tout en ayant un impact positif et solidaire.</p>
          <p>Et parce qu’il n’y a pas de petits dons, chaque participation, qu’elle soit matérielle ou financière, nous sera d’une grande aide et nous vous en remercions d’avance profondément.</p>
        </div>
        <div class="col-md d-none d-lg-block">
          <%= image_tag "photo11.JPG", class: "photo-card" %>
        </div>
      </div>
    <p><mark>La Santerre Cup est une association loi de 1901 depuis 2017</mark>. Si vous êtes un particulier, vous profitez d’une réduction d’impôt de 66% des sommes que vous nous versez, dans la limite de 20% de votre revenu imposable. Ainsi, un don de 100€ à notre association ne vous coûtera après déduction d’impôts que 44€. Si vous êtes une entreprise, la réduction fiscale est de 60% dans la limite de 5/1000 de votre chiffre d’affaires annuel.</p>
  </div>
</div>
<div class="wrapper-gray">
  <div class="container-fluid">
    <h3>Nos différents plans de sponsoring</h1>
      <div class="row">
        <div class="col-md">
          <h4>Bronze<p>Dons inférieurs à 500€</p></h4>
          <p>Accès gratuit à l'événement</p>
          <p>Présence sur la bâche des sponsors</p>
          <p>Présence sur le site internet et la plaquette de l'association</p>
        </div>
        <div class="col-md">
          <h4>Argent<p>Dons compris entre 500€ et 1000€ exclus</p></h4>
          <p>+ Présentation de votre entreprise/activité sur l'événement Facebook (+800 invités)</p>
          <p>+ Mise en avant de votre logo sur notre bâche des sponsors et notre site internet</p>
          <p>+ Possibilité de présence de panneaux publicitaires le jour de l'événement</p>
        </div>
        <div class="col-md">
          <h4>Or <p>Dons supérieurs à 1000€</p></h4>
          <p>+ un des 8 terrains au nom de votre entreprise</p>
          <p>+ un paragraphe de présentation de votre entreprise sur notre page Facebook et notre site internet en tant que partenaire privilégié</p>
          <p>+ mise en place d'une promotion spéciale le jour de l'événement (dans la limite du possible)</p>
        </div>
      </div>
      <div class="align-buttons">
        <%= link_to "Je veux devenir partenaire !", sponsor_path, class: 'btn btn-primary' %>
      </div>
  </div>
</div>
<div class="wrapper-white-navbar">
  <div class="container-fluid">
    <div class="row">
      <h3>Au soutien de la IIIème édition</h3>
      <p>Cette IIIème édition et les dons aux associations n’auraient pas été possibles sans la fidèle participation des joueurs et les dons de nos généreux partenaires ! Toute l’équipe de la Santerre Cup remercie infiniment :</p>
      <div class="col-md">
        <ul class="sponsor-card">
          <li>Agrisanterre</li>
          <li>AGTIV</li>
          <li>Pascal Ammeux</li>
          <li>Artois MotoCulture</li>
          <li>Nicolas Boisleux</li>
          <li>Boutté</li>
          <li>Bruno & Olivier Peugniez</li>
          <li>Yves Carpentier</li>
          <li>La CASA</li>
          <li>CER France</li>
          <li>Consille TP</li>
          <li>Les Garages François Debflex</li>
          <li>Anne-Catherine Decarne</li>
          <li>Decathlon Amiens</li>
          <li>Antoine Deffontaines</li>
        </ul>
      </div>
      <div class="col-md">
        <ul class="sponsor-card">
          <li>Le Domaine du Val</li>
          <li>SARL Douvillé</li>
          <li>SARL Duminiel Ghewy</li>
          <li>Arnaud Dupuy</li>
          <li>EDIM</li>
          <li>Florimond Desprès</li>
          <li>Germicopa</li>
          <li>LMA</li>
          <li>Mention & Co</li>
          <li>Noriap</li>
          <li>Thierry Peugniez</li>
          <li>Pomly</li>
          <li>Pumpkin</li>
          <li>Guy-Marie Sokalski</li>
          <li>Cédric & Jean-François Tavernier</li>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/pages/post_sign_up.html.erb
<h1>Inscription terminée <%= current_user.profile.first_name %> !</h1>

<p>La création de ton compte a bien été enregistrée. Valide ton adresse mail en cliquant sur le lien que nous t’avons envoyé dans le mail de bienvenue. N’oublie de checker tes spams !
</p>

<%= link_to 'Me pré-inscrire', new_participant_path, class: "btn btn-primary" %>